apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.service.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.service.name }}
    idp.platform/team: {{ .Values.service.team }}
    idp.platform/environment: {{ .Values.service.environment }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.service.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.service.name }}
        idp.platform/team: {{ .Values.service.team }}
        idp.platform/environment: {{ .Values.service.environment }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.containerPort }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.containerPort }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.containerPort }}
